import { SignIn, useUser } from "@clerk/nextjs";
import Head from "next/head";

// import Link from "next/link";

import { api } from "~/utils/api";

/* COMPONENTS */
import { LoadingPage } from "~/components/loading";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  const { isLoaded: userLoaded, isSignedIn } = useUser();

  // Return empty div if user isn't loaded yet
  if (!userLoaded) {
    return <LoadingPage />;
  }

  return (
    <>
      <Head>
        <title>CineTrackr</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-row items-center justify-center bg-gradient-to-b from-[#d5bdaf] to-[#edede9]">

        {/* signin section */}

        {!isSignedIn && (
          <div className="flex justify-center">
            <SignIn />
          </div>
        )}

        {isSignedIn && (
          <span>You are signed in</span>
        )}

      </main>


    </>
  );
}
